
/*

SELECT pg_terminate_backend(pid)
FROM pg_stat_activity
WHERE datname = 'hospital_occidente'
  AND pid <> pg_backend_pid();


DROP DATABASE IF EXISTS hospital_occidente;

CREATE DATABASE hospital_occidente
    WITH
    OWNER = user1
    ENCODING = 'UTF8'
    LC_COLLATE = 'C'
    LC_CTYPE = 'C'
    TEMPLATE = template0;
*/



DROP SCHEMA IF EXISTS hospitales_occidente CASCADE;
CREATE SCHEMA hospitales_occidente;
SET search_path TO hospitales_occidente, public;
SET timezone TO 'America/Guatemala';
CREATE EXTENSION IF NOT EXISTS btree_gist WITH SCHEMA public;


/* ============================================================================
   M1. CATÁLOGOS CLÍNICOS Y GEOGRAFÍA (19 TABLAS)
   ============================================================================ */

-- Departamentos de la república de Guatemala.
CREATE TABLE departamento (
    id_departamento INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre          VARCHAR(50) NOT NULL,
    CONSTRAINT pk_departamento        PRIMARY KEY (id_departamento),
    CONSTRAINT uq_departamento_nombre UNIQUE (nombre),
    CONSTRAINT ck_departamento_nombre CHECK (length(trim(nombre)) >= 3)  -- nombre de departamento no vacio
);

-- Municipios pertenecientes a cada departamento.
CREATE TABLE municipio (
    id_municipio    INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_departamento INTEGER     NOT NULL,
    nombre          VARCHAR(80) NOT NULL,
    CONSTRAINT pk_municipio        PRIMARY KEY (id_municipio),
    CONSTRAINT uq_municipio_nombre UNIQUE (id_departamento, nombre),
    CONSTRAINT ck_municipio_nombre CHECK (length(trim(nombre)) >= 2),  -- nombre de municipio no vacio
    CONSTRAINT fk_municipio_departamento FOREIGN KEY (id_departamento)
        REFERENCES departamento (id_departamento) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Dirección habitual reutilizable por personas e instalaciones hospitalarias.
CREATE TABLE direccion (
    id_direccion INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_municipio INTEGER      NOT NULL,
    area         VARCHAR(7)   NOT NULL,
    detalle      VARCHAR(200) NOT NULL,
    CONSTRAINT pk_direccion       PRIMARY KEY (id_direccion),
    CONSTRAINT ck_direccion_area  CHECK (area IN ('Urbana', 'Rural')),  -- clasificacion de area urbana o rural
    CONSTRAINT ck_direccion_det   CHECK (length(trim(detalle)) >= 5),  -- detalle descriptivo suficiente
    CONSTRAINT fk_direccion_municipio FOREIGN KEY (id_municipio)
        REFERENCES municipio (id_municipio) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Catálogo de parentescos reconocidos entre paciente y encargado legal.
CREATE TABLE parentesco (
    id_parentesco INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre        VARCHAR(40) NOT NULL,
    CONSTRAINT pk_parentesco        PRIMARY KEY (id_parentesco),
    CONSTRAINT uq_parentesco_nombre UNIQUE (nombre),
    CONSTRAINT ck_parentesco_nombre CHECK (length(trim(nombre)) >= 3)  -- nombre de parentesco valido
);

-- Especialidades médicas clínicas y quirúrgicas avaladas por la institución.
CREATE TABLE especialidad (
    id_especialidad INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre          VARCHAR(80) NOT NULL,
    tipo            VARCHAR(10) NOT NULL,
    CONSTRAINT pk_especialidad        PRIMARY KEY (id_especialidad),
    CONSTRAINT uq_especialidad_nombre UNIQUE (nombre),
    CONSTRAINT ck_especialidad_tipo   CHECK (tipo IN ('Clinica', 'Quirurgica'))  -- clasificacion clinica o quirurgica
);

-- Catálogo de diagnósticos médicos codificados según estándar CIE-10.
CREATE TABLE diagnostico (
    id_diagnostico INTEGER GENERATED BY DEFAULT AS IDENTITY,
    codigo_cie10   VARCHAR(10)  NOT NULL,
    descripcion    VARCHAR(250) NOT NULL,
    CONSTRAINT pk_diagnostico        PRIMARY KEY (id_diagnostico),
    CONSTRAINT uq_diagnostico_codigo UNIQUE (codigo_cie10),
    CONSTRAINT ck_diagnostico_codigo CHECK (codigo_cie10 ~ '^[A-Z][0-9]{2}(\.[0-9]{1,2})?$')  -- formato estandar de codigo CIE-10
);

-- Tipos de unidad médica de atención y destino.
CREATE TABLE tipo_unidad (
    id_tipo_unidad INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre         VARCHAR(30) NOT NULL,
    CONSTRAINT pk_tipo_unidad        PRIMARY KEY (id_tipo_unidad),
    CONSTRAINT uq_tipo_unidad_nombre UNIQUE (nombre),
    CONSTRAINT ck_tipo_unidad_nombre CHECK (nombre IN ('Consulta externa', 'Emergencias', 'Cirugia', 'Hospitalizacion', 'Otro'))  -- unidades medicas oficiales y destinos externos
);

-- Servicios y especialidades asistenciales ofrecidos en cada unidad.
CREATE TABLE servicio_medico (
    id_servicio    INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_tipo_unidad INTEGER      NOT NULL,
    nombre         VARCHAR(100) NOT NULL,
    activo         BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_servicio_medico        PRIMARY KEY (id_servicio),
    CONSTRAINT uq_servicio_medico_nombre UNIQUE (id_tipo_unidad, nombre),
    CONSTRAINT ck_servicio_medico_nombre CHECK (length(trim(nombre)) >= 3),  -- nombre de servicio asistencial valido
    CONSTRAINT fk_servicio_tipo_unidad FOREIGN KEY (id_tipo_unidad)
        REFERENCES tipo_unidad (id_tipo_unidad) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Turnos laborales de atención médica y guardias.
CREATE TABLE turno (
    id_turno    INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre      VARCHAR(40) NOT NULL,
    hora_inicio TIME        NOT NULL,
    hora_fin    TIME        NOT NULL,
    CONSTRAINT pk_turno        PRIMARY KEY (id_turno),
    CONSTRAINT uq_turno_nombre UNIQUE (nombre),
    CONSTRAINT ck_turno_horas  CHECK (hora_inicio <> hora_fin)  -- turno laboral con duracion mayor a cero
);

-- Métodos de pago autorizados en recepción y cajas de cobro.
CREATE TABLE metodo_pago (
    id_metodo_pago INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre         VARCHAR(30) NOT NULL,
    CONSTRAINT pk_metodo_pago        PRIMARY KEY (id_metodo_pago),
    CONSTRAINT uq_metodo_pago_nombre UNIQUE (nombre),
    CONSTRAINT ck_metodo_pago_nombre CHECK (length(trim(nombre)) >= 3)  -- descripcion de metodo de pago valida
);

-- Catálogo de medicamentos recetables con su presentación farmacéutica.
CREATE TABLE medicamento (
    id_medicamento INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre         VARCHAR(120) NOT NULL,
    presentacion   VARCHAR(80),
    CONSTRAINT pk_medicamento        PRIMARY KEY (id_medicamento),
    CONSTRAINT uq_medicamento_nombre UNIQUE (nombre, presentacion),
    CONSTRAINT ck_medicamento_nombre CHECK (length(trim(nombre)) >= 2)  -- nombre de medicamento valido
);

-- Catálogo de pruebas diagnósticas y análisis clínicos de laboratorio.
CREATE TABLE examen_laboratorio (
    id_examen INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre    VARCHAR(120) NOT NULL,
    CONSTRAINT pk_examen_laboratorio        PRIMARY KEY (id_examen),
    CONSTRAINT uq_examen_laboratorio_nombre UNIQUE (nombre),
    CONSTRAINT ck_examen_lab_nombre         CHECK (length(trim(nombre)) >= 3)  -- nombre de examen diagnostico valido
);

-- Tipos de anestesia administrables en procedimientos quirúrgicos.
CREATE TABLE tipo_anestesia (
    id_tipo_anestesia INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre            VARCHAR(50) NOT NULL,
    CONSTRAINT pk_tipo_anestesia        PRIMARY KEY (id_tipo_anestesia),
    CONSTRAINT uq_tipo_anestesia_nombre UNIQUE (nombre),
    CONSTRAINT ck_tipo_anestesia_nombre CHECK (length(trim(nombre)) >= 3)  -- tipo de tecnica anestesica valida
);

-- Procedimientos quirúrgicos clasificados por especialidad médica.
CREATE TABLE procedimiento_quirurgico (
    id_procedimiento INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_especialidad  INTEGER      NOT NULL,
    nombre           VARCHAR(150) NOT NULL,
    descripcion      VARCHAR(300),
    CONSTRAINT pk_procedimiento_quirurgico        PRIMARY KEY (id_procedimiento),
    CONSTRAINT uq_procedimiento_quirurgico_nombre UNIQUE (nombre),
    CONSTRAINT ck_proc_quirurgico_nombre          CHECK (length(trim(nombre)) >= 4),  -- nombre de intervencion quirurgica valida
    CONSTRAINT fk_procedimiento_especialidad FOREIGN KEY (id_especialidad)
        REFERENCES especialidad (id_especialidad) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Insumos consumibles y materiales quirúrgicos utilizados en la atención.
CREATE TABLE insumo (
    id_insumo   INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre      VARCHAR(120) NOT NULL,
    descripcion VARCHAR(300),
    material    VARCHAR(80),
    tipo        VARCHAR(10)  NOT NULL,
    CONSTRAINT pk_insumo        PRIMARY KEY (id_insumo),
    CONSTRAINT uq_insumo_nombre UNIQUE (nombre),
    CONSTRAINT ck_insumo_tipo   CHECK (tipo IN ('Medico', 'Quirurgico', 'Otro'))  -- clasificacion oficial del tipo de insumo
);

-- Instrumental quirúrgico reutilizable y su función operativa.
CREATE TABLE instrumento (
    id_instrumento INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre         VARCHAR(120) NOT NULL,
    descripcion    VARCHAR(300),
    tipo           VARCHAR(10)  NOT NULL,
    funcion        VARCHAR(12)  NOT NULL,
    CONSTRAINT pk_instrumento        PRIMARY KEY (id_instrumento),
    CONSTRAINT uq_instrumento_nombre UNIQUE (nombre),
    CONSTRAINT ck_instrumento_tipo    CHECK (tipo IN ('Medico', 'Quirurgico', 'Otro')),  -- clasificacion de instrumento medico o quirurgico
    CONSTRAINT ck_instrumento_funcion CHECK (funcion IN ('Corte', 'Contenido', 'Hemostatica', 'Retractor', 'Accesorio', 'Implante', 'Otro'))  -- funcion quirurgica del instrumental
);

-- Equipos biomédicos y electromédicos asignables.
CREATE TABLE equipo (
    id_equipo   INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre      VARCHAR(120) NOT NULL,
    descripcion VARCHAR(300),
    tipo        VARCHAR(10)  NOT NULL,
    funcion     VARCHAR(15)  NOT NULL,
    CONSTRAINT pk_equipo        PRIMARY KEY (id_equipo),
    CONSTRAINT uq_equipo_nombre UNIQUE (nombre),
    CONSTRAINT ck_equipo_tipo    CHECK (tipo IN ('Medico', 'Quirurgico', 'Otro')),  -- clasificacion del equipo medico o quirurgico
    CONSTRAINT ck_equipo_funcion CHECK (funcion IN ('Exploracion', 'Diagnostico', 'Tratamiento', 'Rehabilitacion', 'Otro'))  -- funcion asistencial del equipo
);

-- Momentos de control del proceso quirúrgico según fase clínica.
CREATE TABLE momento_quirurgico (
    id_momento INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre     VARCHAR(60) NOT NULL,
    fase       VARCHAR(15) NOT NULL,
    orden      SMALLINT    NOT NULL,
    CONSTRAINT pk_momento_quirurgico        PRIMARY KEY (id_momento),
    CONSTRAINT uq_momento_quirurgico_nombre UNIQUE (nombre),
    CONSTRAINT ck_momento_fase  CHECK (fase IN ('Preoperatorio', 'Intraoperatorio', 'Postoperatorio')),  -- fase obligatoria del proceso quirurgico
    CONSTRAINT ck_momento_orden CHECK (orden > 0)  -- secuencia cronologica positiva
);

-- Ítems evaluables en los checklists de seguridad y calidad quirúrgica.
CREATE TABLE item_verificacion (
    id_item        INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_momento     INTEGER      NOT NULL,
    descripcion    VARCHAR(250) NOT NULL,
    tipo_resultado VARCHAR(15)  NOT NULL,
    orden          SMALLINT     NOT NULL DEFAULT 1,
    CONSTRAINT pk_item_verificacion      PRIMARY KEY (id_item),
    CONSTRAINT uq_item_verificacion_desc UNIQUE (id_momento, descripcion),
    CONSTRAINT ck_item_tipo_resultado    CHECK (tipo_resultado IN ('Exito o fallo', 'Aceptabilidad')),  -- escala de calificacion del item
    CONSTRAINT ck_item_orden             CHECK (orden > 0),  -- orden correlativo positivo
    CONSTRAINT fk_item_momento FOREIGN KEY (id_momento)
        REFERENCES momento_quirurgico (id_momento) ON DELETE RESTRICT ON UPDATE CASCADE
);


/* ============================================================================
   M2. ESTRUCTURA HOSPITALARIA (4 TABLAS)
   ============================================================================ */

-- Hospitales pertenecientes a la red y centros externos de referencia/traslado.
CREATE TABLE hospital (
    id_hospital  INTEGER GENERATED BY DEFAULT AS IDENTITY,
    codigo       VARCHAR(10)  NOT NULL,
    nombre       VARCHAR(120) NOT NULL,
    id_direccion INTEGER      NOT NULL,
    telefono     VARCHAR(15),
    correo       VARCHAR(100),
    es_interno   BOOLEAN      NOT NULL DEFAULT TRUE,
    activo       BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_hospital        PRIMARY KEY (id_hospital),
    CONSTRAINT uq_hospital_codigo UNIQUE (codigo),
    CONSTRAINT uq_hospital_nombre UNIQUE (nombre),
    CONSTRAINT ck_hospital_codigo   CHECK (codigo ~ '^[A-Z0-9\-]{3,10}$'),  -- formato alfanumerico de codigo hospitalario
    CONSTRAINT ck_hospital_telefono CHECK (telefono IS NULL OR telefono ~ '^(\+?502)?[0-9]{8}$'),  -- numero telefonico nacional de 8 digitos con codigo optativo
    CONSTRAINT ck_hospital_correo   CHECK (correo IS NULL OR correo ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),  -- correo electronico con formato corporativo estandar
    CONSTRAINT fk_hospital_direccion FOREIGN KEY (id_direccion)
        REFERENCES direccion (id_direccion) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Unidades asistenciales habilitadas por cada hospital interno de la red.
CREATE TABLE unidad_hospital (
    id_unidad_hospital INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_hospital        INTEGER NOT NULL,
    id_tipo_unidad     INTEGER NOT NULL,
    CONSTRAINT pk_unidad_hospital PRIMARY KEY (id_unidad_hospital),
    CONSTRAINT uq_unidad_hospital UNIQUE (id_hospital, id_tipo_unidad),
    CONSTRAINT fk_unidad_hospital FOREIGN KEY (id_hospital)
        REFERENCES hospital (id_hospital) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_unidad_tipo FOREIGN KEY (id_tipo_unidad)
        REFERENCES tipo_unidad (id_tipo_unidad) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Camillas y quirófanos habilitados físicamente en cada unidad hospitalaria.
CREATE TABLE espacio_atencion (
    id_espacio         INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_unidad_hospital INTEGER     NOT NULL,
    tipo               VARCHAR(10) NOT NULL,
    codigo             VARCHAR(15) NOT NULL,
    habilitado         BOOLEAN     NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_espacio_atencion PRIMARY KEY (id_espacio),
    CONSTRAINT uq_espacio_codigo   UNIQUE (id_unidad_hospital, codigo),
    CONSTRAINT ck_espacio_tipo     CHECK (tipo IN ('Camilla', 'Quirofano')),  -- clasificacion de espacio entre camilla o quirofano
    CONSTRAINT ck_espacio_codigo   CHECK (length(trim(codigo)) >= 2),  -- identificador de espacio no vacio
    CONSTRAINT fk_espacio_unidad FOREIGN KEY (id_unidad_hospital)
        REFERENCES unidad_hospital (id_unidad_hospital) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Clínicas y consultorios físicos asignados a consulta externa en cada hospital.
CREATE TABLE clinica (
    id_clinica     INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_hospital    INTEGER     NOT NULL,
    numero_clinica VARCHAR(10) NOT NULL,
    habilitada     BOOLEAN     NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_clinica        PRIMARY KEY (id_clinica),
    CONSTRAINT uq_clinica_numero UNIQUE (id_hospital, numero_clinica),
    CONSTRAINT ck_clinica_numero CHECK (length(trim(numero_clinica)) >= 1),  -- numero o nomenclatura de clinica valida
    CONSTRAINT fk_clinica_hospital FOREIGN KEY (id_hospital)
        REFERENCES hospital (id_hospital) ON DELETE RESTRICT ON UPDATE CASCADE
);


/* ============================================================================
   M3. PERSONAS Y PERSONAL (8 TABLAS)
   ============================================================================ */

-- Entidad supertipo con datos demográficos y de identificación de personas.
CREATE TABLE persona (
    id_persona       INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombres          VARCHAR(100) NOT NULL,
    apellidos        VARCHAR(100) NOT NULL,
    dpi              VARCHAR(13),
    fecha_nacimiento DATE         NOT NULL,
    sexo             VARCHAR(9)   NOT NULL,
    telefono         VARCHAR(15),
    id_direccion     INTEGER      NOT NULL,
    creado_en        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_persona            PRIMARY KEY (id_persona),
    CONSTRAINT uq_persona_dpi        UNIQUE (dpi),
    CONSTRAINT ck_persona_nombres    CHECK (length(trim(nombres)) >= 2),  -- nombres de persona validos
    CONSTRAINT ck_persona_apellidos  CHECK (length(trim(apellidos)) >= 2),  -- apellidos de persona validos
    CONSTRAINT ck_persona_dpi        CHECK (dpi IS NULL OR dpi ~ '^[0-9]{13}$'),  -- DPI guatemalteco de 13 digitos numericos
    CONSTRAINT ck_persona_sexo       CHECK (sexo IN ('Masculino', 'Femenino')),  -- clasificacion de sexo biologico
    CONSTRAINT ck_persona_nacimiento CHECK (fecha_nacimiento >= DATE '1900-01-01'),  -- fecha de nacimiento contemporanea verificable
    CONSTRAINT ck_persona_telefono   CHECK (telefono IS NULL OR telefono ~ '^(\+?502)?[0-9]{8}$'),  -- telefono de 8 digitos con codigo optativo
    CONSTRAINT fk_persona_direccion FOREIGN KEY (id_direccion)
        REFERENCES direccion (id_direccion) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Subtipo de persona correspondiente a pacientes atendidos con expediente clínico.
CREATE TABLE paciente (
    id_paciente             INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_persona              INTEGER     NOT NULL,
    no_expediente           VARCHAR(20) NOT NULL,
    estado_civil            VARCHAR(15) NOT NULL DEFAULT 'Soltero',
    no_seguro_social        VARCHAR(20),
    religion                VARCHAR(50),
    ocupacion               VARCHAR(80),
    id_municipio_nacimiento INTEGER,
    CONSTRAINT pk_paciente               PRIMARY KEY (id_paciente),
    CONSTRAINT uq_paciente_persona       UNIQUE (id_persona),
    CONSTRAINT uq_paciente_expediente    UNIQUE (no_expediente),
    CONSTRAINT uq_paciente_seguro_social UNIQUE (no_seguro_social),
    CONSTRAINT ck_paciente_expediente   CHECK (length(trim(no_expediente)) >= 3),  -- numero de expediente no vacio
    CONSTRAINT ck_paciente_estado_civil CHECK (estado_civil IN ('Soltero', 'Casado', 'Divorciado', 'Viudo', 'Union de hecho')),  -- estado civil segun catalogo civil
    CONSTRAINT fk_paciente_persona FOREIGN KEY (id_persona)
        REFERENCES persona (id_persona) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_paciente_municipio_nac FOREIGN KEY (id_municipio_nacimiento)
        REFERENCES municipio (id_municipio) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Relación asociativa entre pacientes y sus encargados legales/familiares (N:M).
CREATE TABLE paciente_encargado (
    id_paciente_encargado INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_paciente           INTEGER NOT NULL,
    id_persona            INTEGER NOT NULL,
    id_parentesco         INTEGER NOT NULL,
    es_principal          BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_paciente_encargado PRIMARY KEY (id_paciente_encargado),
    CONSTRAINT uq_paciente_encargado UNIQUE (id_paciente, id_persona),
    CONSTRAINT fk_pacenc_paciente FOREIGN KEY (id_paciente)
        REFERENCES paciente (id_paciente) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_pacenc_persona FOREIGN KEY (id_persona)
        REFERENCES persona (id_persona) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_pacenc_parentesco FOREIGN KEY (id_parentesco)
        REFERENCES parentesco (id_parentesco) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Subtipo de persona para colaboradores y empleados asistenciales/administrativos.
CREATE TABLE personal (
    id_personal   INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_persona    INTEGER     NOT NULL,
    tipo_personal VARCHAR(30) NOT NULL,
    activo        BOOLEAN     NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_personal         PRIMARY KEY (id_personal),
    CONSTRAINT uq_personal_persona UNIQUE (id_persona),
    CONSTRAINT ck_personal_tipo    CHECK (tipo_personal IN ('Medico', 'Enfermero', 'Practicante de medicina', 'Practicante de enfermeria', 'Administrativo')),  -- clasificacion profesional del colaborador
    CONSTRAINT fk_personal_persona FOREIGN KEY (id_persona)
        REFERENCES persona (id_persona) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Subtipo de personal para médicos con registro colegiado y régimen laboral.
CREATE TABLE medico (
    id_personal        INTEGER       NOT NULL,
    no_colegiado       VARCHAR(20)   NOT NULL,
    condicion          VARCHAR(10)   NOT NULL,
    institucion_origen VARCHAR(120),
    tarifa_consulta    NUMERIC(10,2) NOT NULL DEFAULT 0,
    CONSTRAINT pk_medico           PRIMARY KEY (id_personal),
    CONSTRAINT uq_medico_colegiado UNIQUE (no_colegiado),
    CONSTRAINT ck_medico_colegiado CHECK (length(trim(no_colegiado)) >= 3),  -- numero de colegiado activo valido
    CONSTRAINT ck_medico_condicion CHECK (condicion IN ('Planta', 'Residente', 'Interno', 'Externo')),  -- condicion laboral de contratacion del facultativo
    CONSTRAINT ck_medico_tarifa    CHECK (tarifa_consulta >= 0),  -- honorario de consulta medica no negativo
    CONSTRAINT ck_medico_externo   CHECK ((condicion = 'Externo' AND institucion_origen IS NOT NULL) OR (condicion <> 'Externo' AND institucion_origen IS NULL)),  -- institucion de procedencia obligatoria exclusivamente para medicos externos
    CONSTRAINT fk_medico_personal FOREIGN KEY (id_personal)
        REFERENCES personal (id_personal) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Especialidades acreditadas de cada médico dentro del hospital (N:M).
CREATE TABLE medico_especialidad (
    id_medico       INTEGER NOT NULL,
    id_especialidad INTEGER NOT NULL,
    es_principal    BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_medico_especialidad PRIMARY KEY (id_medico, id_especialidad),
    CONSTRAINT fk_medesp_medico FOREIGN KEY (id_medico)
        REFERENCES medico (id_personal) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_medesp_especialidad FOREIGN KEY (id_especialidad)
        REFERENCES especialidad (id_especialidad) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Asignación operativa de personal a unidades hospitalarias y turnos de trabajo.
CREATE TABLE asignacion_personal (
    id_asignacion      INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_personal        INTEGER NOT NULL,
    id_unidad_hospital INTEGER NOT NULL,
    id_turno           INTEGER NOT NULL,
    fecha_inicio       DATE    NOT NULL,
    fecha_fin          DATE,
    CONSTRAINT pk_asignacion_personal PRIMARY KEY (id_asignacion),
    CONSTRAINT uq_asignacion_personal UNIQUE (id_personal, id_unidad_hospital, id_turno, fecha_inicio),
    CONSTRAINT ck_asignacion_fechas   CHECK (fecha_fin IS NULL OR fecha_fin >= fecha_inicio),  -- vigencia de asignacion coherente sin fin anterior al inicio
    CONSTRAINT fk_asignacion_personal FOREIGN KEY (id_personal)
        REFERENCES personal (id_personal) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_asignacion_unidad FOREIGN KEY (id_unidad_hospital)
        REFERENCES unidad_hospital (id_unidad_hospital) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_asignacion_turno FOREIGN KEY (id_turno)
        REFERENCES turno (id_turno) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Horario semanal de atención ambulatoria de cada médico en clínica matutina.
CREATE TABLE horario_medico (
    id_horario  INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_medico   INTEGER  NOT NULL,
    id_clinica  INTEGER  NOT NULL,
    dia_semana  SMALLINT NOT NULL,
    hora_inicio TIME     NOT NULL,
    hora_fin    TIME     NOT NULL,
    CONSTRAINT pk_horario_medico   PRIMARY KEY (id_horario),
    CONSTRAINT uq_horario_medico   UNIQUE (id_medico, id_clinica, dia_semana, hora_inicio),
    CONSTRAINT ck_horario_dia      CHECK (dia_semana BETWEEN 1 AND 7),  -- dia de la semana del 1 (lunes) al 7 (domingo)
    CONSTRAINT ck_horario_horas    CHECK (hora_fin > hora_inicio),  -- horario laboral con hora de fin posterior al inicio
    CONSTRAINT ck_horario_matutino CHECK (hora_inicio >= TIME '06:00' AND hora_fin <= TIME '13:00'),  -- atencion de consulta externa restringida al turno matutino
    CONSTRAINT fk_horario_medico FOREIGN KEY (id_medico)
        REFERENCES medico (id_personal) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_horario_clinica FOREIGN KEY (id_clinica)
        REFERENCES clinica (id_clinica) ON DELETE RESTRICT ON UPDATE CASCADE
);


/* ============================================================================
   M4. NÚCLEO CLÍNICO COMÚN (7 TABLAS)
   ============================================================================ */

-- Episodio clínico: ciclo continuo de atención del paciente hasta su facturación.
CREATE TABLE episodio (
    id_episodio    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_paciente    INTEGER     NOT NULL,
    id_hospital    INTEGER     NOT NULL,
    fecha_apertura TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_cierre   TIMESTAMPTZ,
    CONSTRAINT pk_episodio        PRIMARY KEY (id_episodio),
    CONSTRAINT ck_episodio_fechas CHECK (fecha_cierre IS NULL OR fecha_cierre >= fecha_apertura),  -- fecha de alta o cierre posterior a la apertura
    CONSTRAINT fk_episodio_paciente FOREIGN KEY (id_paciente)
        REFERENCES paciente (id_paciente) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_episodio_hospital FOREIGN KEY (id_hospital)
        REFERENCES hospital (id_hospital) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Registro periódico de signos vitales y mediciones somatométricas en el episodio.
CREATE TABLE registro_signos_vitales (
    id_signos_vitales       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_episodio             BIGINT      NOT NULL,
    fecha_hora              TIMESTAMPTZ NOT NULL DEFAULT now(),
    presion_sistolica       SMALLINT,
    presion_diastolica      SMALLINT,
    frecuencia_cardiaca     SMALLINT,
    frecuencia_respiratoria SMALLINT,
    temperatura_c           NUMERIC(4,1),
    saturacion_oxigeno      SMALLINT,
    peso_kg                 NUMERIC(5,2),
    talla_cm                NUMERIC(5,1),
    id_personal             INTEGER,
    CONSTRAINT pk_registro_signos_vitales PRIMARY KEY (id_signos_vitales),
    CONSTRAINT ck_signos_sistolica  CHECK (presion_sistolica IS NULL OR presion_sistolica BETWEEN 40 AND 300),  -- rango fisiologico de presion sistolica
    CONSTRAINT ck_signos_diastolica CHECK (presion_diastolica IS NULL OR presion_diastolica BETWEEN 20 AND 200),  -- rango fisiologico de presion diastolica
    CONSTRAINT ck_signos_presion    CHECK (presion_sistolica IS NULL OR presion_diastolica IS NULL OR presion_sistolica > presion_diastolica),  -- coherencia hemodinamica: sistolica superior a diastolica
    CONSTRAINT ck_signos_fc         CHECK (frecuencia_cardiaca IS NULL OR frecuencia_cardiaca BETWEEN 20 AND 300),  -- frecuencia cardiaca biometricamente factible
    CONSTRAINT ck_signos_fr         CHECK (frecuencia_respiratoria IS NULL OR frecuencia_respiratoria BETWEEN 4 AND 80),  -- frecuencia respiratoria biometricamente factible
    CONSTRAINT ck_signos_temp       CHECK (temperatura_c IS NULL OR temperatura_c BETWEEN 25.0 AND 45.0),  -- temperatura corporal factible en grados Celsius
    CONSTRAINT ck_signos_sato2      CHECK (saturacion_oxigeno IS NULL OR saturacion_oxigeno BETWEEN 0 AND 100),  -- porcentaje de oximetria de pulso entre 0 y 100
    CONSTRAINT ck_signos_peso       CHECK (peso_kg IS NULL OR (peso_kg > 0 AND peso_kg <= 500.0)),  -- peso corporal razonable en kilogramos
    CONSTRAINT ck_signos_talla      CHECK (talla_cm IS NULL OR talla_cm BETWEEN 20.0 AND 250.0),  -- estatura corporal razonable en centimetros
    CONSTRAINT fk_signos_episodio FOREIGN KEY (id_episodio)
        REFERENCES episodio (id_episodio) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_signos_personal FOREIGN KEY (id_personal)
        REFERENCES personal (id_personal) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Ficha de ingreso clínico a Emergencias, Cirugía u Hospitalización.
CREATE TABLE ingreso (
    id_ingreso                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_episodio               BIGINT       NOT NULL,
    id_unidad_hospital        INTEGER      NOT NULL,
    id_servicio               INTEGER      NOT NULL,
    fecha_hora_ingreso        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    motivo_ingreso            VARCHAR(300) NOT NULL,
    id_diagnostico_presuntivo INTEGER      NOT NULL,
    id_medico                 INTEGER      NOT NULL,
    id_espacio                INTEGER,
    id_paciente_encargado     INTEGER,
    estado_actual_paciente    VARCHAR(500) NOT NULL,
    prioridad_triage          SMALLINT,
    dias_estimados_estancia   SMALLINT,
    CONSTRAINT pk_ingreso        PRIMARY KEY (id_ingreso),
    CONSTRAINT ck_ingreso_motivo CHECK (length(trim(motivo_ingreso)) >= 5),  -- motivo clinico de admision descriptivo
    CONSTRAINT ck_ingreso_triage CHECK (prioridad_triage IS NULL OR prioridad_triage BETWEEN 1 AND 5),  -- nivel de triage del 1 (emergencia critica) al 5 (no urgente)
    CONSTRAINT ck_ingreso_dias   CHECK (dias_estimados_estancia IS NULL OR dias_estimados_estancia > 0),  -- dias estimados de estancia mayores a cero
    CONSTRAINT fk_ingreso_episodio FOREIGN KEY (id_episodio)
        REFERENCES episodio (id_episodio) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_ingreso_unidad FOREIGN KEY (id_unidad_hospital)
        REFERENCES unidad_hospital (id_unidad_hospital) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_ingreso_servicio FOREIGN KEY (id_servicio)
        REFERENCES servicio_medico (id_servicio) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_ingreso_diagnostico FOREIGN KEY (id_diagnostico_presuntivo)
        REFERENCES diagnostico (id_diagnostico) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_ingreso_medico FOREIGN KEY (id_medico)
        REFERENCES medico (id_personal) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_ingreso_espacio FOREIGN KEY (id_espacio)
        REFERENCES espacio_atencion (id_espacio) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_ingreso_encargado FOREIGN KEY (id_paciente_encargado)
        REFERENCES paciente_encargado (id_paciente_encargado) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Ficha de traslado inter-unidades u hospitales de origen y destino.
CREATE TABLE traslado (
    id_traslado             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_episodio             BIGINT       NOT NULL,
    fecha_hora              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    id_medico_indica        INTEGER      NOT NULL,
    id_hospital_origen      INTEGER      NOT NULL,
    id_tipo_unidad_origen   INTEGER      NOT NULL,
    id_servicio_origen      INTEGER,
    id_hospital_destino     INTEGER      NOT NULL,
    id_tipo_unidad_destino  INTEGER      NOT NULL,
    id_servicio_destino     INTEGER,
    id_ingreso_destino      BIGINT,
    motivo                  VARCHAR(300) NOT NULL,
    consentimiento_otorgado BOOLEAN      NOT NULL DEFAULT FALSE,
    id_paciente_encargado   INTEGER,
    CONSTRAINT pk_traslado                 PRIMARY KEY (id_traslado),
    CONSTRAINT uq_traslado_ingreso_destino UNIQUE (id_ingreso_destino),
    CONSTRAINT ck_traslado_motivo          CHECK (length(trim(motivo)) >= 5),  -- justificacion clinica de traslado valida
    CONSTRAINT ck_traslado_origen_destino  CHECK (id_hospital_origen <> id_hospital_destino OR id_tipo_unidad_origen <> id_tipo_unidad_destino),  -- el origen y destino del traslado deben ser diferentes
    CONSTRAINT fk_traslado_episodio FOREIGN KEY (id_episodio)
        REFERENCES episodio (id_episodio) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_traslado_medico FOREIGN KEY (id_medico_indica)
        REFERENCES medico (id_personal) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_traslado_hosp_origen FOREIGN KEY (id_hospital_origen)
        REFERENCES hospital (id_hospital) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_traslado_tipo_origen FOREIGN KEY (id_tipo_unidad_origen)
        REFERENCES tipo_unidad (id_tipo_unidad) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_traslado_serv_origen FOREIGN KEY (id_servicio_origen)
        REFERENCES servicio_medico (id_servicio) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_traslado_hosp_destino FOREIGN KEY (id_hospital_destino)
        REFERENCES hospital (id_hospital) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_traslado_tipo_destino FOREIGN KEY (id_tipo_unidad_destino)
        REFERENCES tipo_unidad (id_tipo_unidad) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_traslado_serv_destino FOREIGN KEY (id_servicio_destino)
        REFERENCES servicio_medico (id_servicio) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_traslado_ingreso_destino FOREIGN KEY (id_ingreso_destino)
        REFERENCES ingreso (id_ingreso) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_traslado_encargado FOREIGN KEY (id_paciente_encargado)
        REFERENCES paciente_encargado (id_paciente_encargado) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Ficha de egreso y alta médica que cierra un ingreso hospitalario (1:1).
CREATE TABLE egreso (
    id_egreso                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_ingreso                BIGINT       NOT NULL,
    fecha_hora_egreso         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    id_diagnostico_principal  INTEGER      NOT NULL,
    motivo_egreso             VARCHAR(300) NOT NULL,
    id_medico                 INTEGER      NOT NULL,
    codigo_egreso             VARCHAR(10)  NOT NULL,
    egreso_sin_consentimiento BOOLEAN      NOT NULL DEFAULT FALSE,
    motivo_sin_consentimiento VARCHAR(300),
    id_traslado               BIGINT,
    id_hospital_referido      INTEGER,
    CONSTRAINT pk_egreso                   PRIMARY KEY (id_egreso),
    CONSTRAINT uq_egreso_ingreso           UNIQUE (id_ingreso),
    CONSTRAINT uq_egreso_traslado          UNIQUE (id_traslado),
    CONSTRAINT ck_egreso_motivo            CHECK (length(trim(motivo_egreso)) >= 4),  -- motivo de egreso clinico valido
    CONSTRAINT ck_egreso_codigo            CHECK (codigo_egreso IN ('Vivo', 'Muerto', 'Embarazo', 'Parto')),  -- codigos de clasificacion internacional del alta
    CONSTRAINT ck_egreso_sin_consentimiento CHECK ((egreso_sin_consentimiento AND motivo_sin_consentimiento IS NOT NULL) OR (NOT egreso_sin_consentimiento AND motivo_sin_consentimiento IS NULL)),  -- justificacion obligatoria exclusivamente cuando el paciente egresa contra indicacion medica
    CONSTRAINT fk_egreso_ingreso FOREIGN KEY (id_ingreso)
        REFERENCES ingreso (id_ingreso) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_egreso_diagnostico FOREIGN KEY (id_diagnostico_principal)
        REFERENCES diagnostico (id_diagnostico) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_egreso_medico FOREIGN KEY (id_medico)
        REFERENCES medico (id_personal) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_egreso_traslado FOREIGN KEY (id_traslado)
        REFERENCES traslado (id_traslado) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_egreso_hospital_referido FOREIGN KEY (id_hospital_referido)
        REFERENCES hospital (id_hospital) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Diagnósticos secundarios identificados en el paciente al momento del egreso (N:M).
CREATE TABLE egreso_diagnostico_secundario (
    id_egreso      BIGINT  NOT NULL,
    id_diagnostico INTEGER NOT NULL,
    CONSTRAINT pk_egreso_diag_secundario PRIMARY KEY (id_egreso, id_diagnostico),
    CONSTRAINT fk_egdiag_egreso FOREIGN KEY (id_egreso)
        REFERENCES egreso (id_egreso) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_egdiag_diagnostico FOREIGN KEY (id_diagnostico)
        REFERENCES diagnostico (id_diagnostico) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Insumos médicos y quirúrgicos consumidos por el paciente durante la estancia.
CREATE TABLE consumo_insumo (
    id_consumo_insumo BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_ingreso        BIGINT      NOT NULL,
    id_insumo         INTEGER     NOT NULL,
    cantidad          INTEGER     NOT NULL,
    fecha_hora        TIMESTAMPTZ NOT NULL DEFAULT now(),
    id_personal       INTEGER,
    CONSTRAINT pk_consumo_insumo   PRIMARY KEY (id_consumo_insumo),
    CONSTRAINT ck_consumo_cantidad CHECK (cantidad > 0),  -- cantidad dispensada estrictamente positiva
    CONSTRAINT fk_consumo_ingreso FOREIGN KEY (id_ingreso)
        REFERENCES ingreso (id_ingreso) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_consumo_insumo FOREIGN KEY (id_insumo)
        REFERENCES insumo (id_insumo) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_consumo_personal FOREIGN KEY (id_personal)
        REFERENCES personal (id_personal) ON DELETE RESTRICT ON UPDATE CASCADE
);


/* ============================================================================
   M5. CONSULTA EXTERNA (6 TABLAS)
   ============================================================================ */

-- Citas médicas programadas y trazabilidad completa de su ciclo de vida.
CREATE TABLE cita (
    id_cita                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_paciente            INTEGER      NOT NULL,
    id_medico              INTEGER      NOT NULL,
    id_clinica             INTEGER      NOT NULL,
    fecha_hora             TIMESTAMPTZ  NOT NULL,
    canal_asignacion       VARCHAR(20)  NOT NULL,
    tipo_consulta          VARCHAR(12)  NOT NULL,
    id_hospital_referente  INTEGER,
    estado                 VARCHAR(13)  NOT NULL DEFAULT 'Programada',
    fecha_cancelacion      TIMESTAMPTZ,
    motivo_cancelacion     VARCHAR(200),
    cancelacion_notificada BOOLEAN,
    id_cita_anterior       BIGINT,
    id_cita_recargo_origen BIGINT,
    creada_en              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_cita                   PRIMARY KEY (id_cita),
    CONSTRAINT ck_cita_canal             CHECK (canal_asignacion IN ('Telefono', 'Correo institucional', 'Recepcion general')),  -- canal valido de agendamiento
    CONSTRAINT ck_cita_tipo              CHECK (tipo_consulta IN ('Primera vez', 'Reconsulta', 'Referido')),  -- modalidad de atencion ambulatoria que rige la tarifa
    CONSTRAINT ck_cita_estado            CHECK (estado IN ('Programada', 'Realizada', 'Reprogramada', 'Cancelada')),  -- estados validos de gestion de la cita
    CONSTRAINT ck_cita_referente         CHECK ((tipo_consulta = 'Referido' AND id_hospital_referente IS NOT NULL) OR (tipo_consulta <> 'Referido' AND id_hospital_referente IS NULL)),  -- centro remitente requerido exclusivamente para pacientes referidos
    CONSTRAINT ck_cita_cancelacion_datos CHECK ((estado = 'Cancelada') OR (fecha_cancelacion IS NULL AND motivo_cancelacion IS NULL AND cancelacion_notificada IS NULL)),  -- detalles de anulacion exclusivos de citas canceladas
    CONSTRAINT ck_cita_cancelacion_aviso CHECK (estado <> 'Cancelada' OR cancelacion_notificada IS NOT NULL),  -- registro obligatorio sobre si la cancelacion fue notificada con anticipacion
    CONSTRAINT fk_cita_paciente FOREIGN KEY (id_paciente)
        REFERENCES paciente (id_paciente) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_cita_medico FOREIGN KEY (id_medico)
        REFERENCES medico (id_personal) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_cita_clinica FOREIGN KEY (id_clinica)
        REFERENCES clinica (id_clinica) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_cita_hospital_referente FOREIGN KEY (id_hospital_referente)
        REFERENCES hospital (id_hospital) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_cita_anterior FOREIGN KEY (id_cita_anterior)
        REFERENCES cita (id_cita) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_cita_recargo_origen FOREIGN KEY (id_cita_recargo_origen)
        REFERENCES cita (id_cita) ON DELETE SET NULL ON UPDATE CASCADE
);

-- Consulta médica efectuada (ficha de consulta del paciente), vinculada 1:1 a la cita.
CREATE TABLE consulta (
    id_consulta         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_cita             BIGINT      NOT NULL,
    id_episodio         BIGINT      NOT NULL,
    fecha_hora          TIMESTAMPTZ NOT NULL DEFAULT now(),
    id_diagnostico      INTEGER     NOT NULL,
    otros_datos_interes TEXT,
    notas_observaciones TEXT,
    CONSTRAINT pk_consulta      PRIMARY KEY (id_consulta),
    CONSTRAINT uq_consulta_cita UNIQUE (id_cita),
    CONSTRAINT fk_consulta_cita FOREIGN KEY (id_cita)
        REFERENCES cita (id_cita) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_consulta_episodio FOREIGN KEY (id_episodio)
        REFERENCES episodio (id_episodio) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_consulta_diagnostico FOREIGN KEY (id_diagnostico)
        REFERENCES diagnostico (id_diagnostico) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Receta médica emitida durante la consulta ambulatoria.
CREATE TABLE receta (
    id_receta            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_consulta          BIGINT NOT NULL,
    fecha_emision        DATE   NOT NULL DEFAULT CURRENT_DATE,
    id_cita_proxima      BIGINT,
    orientacion_paciente TEXT,
    CONSTRAINT pk_receta              PRIMARY KEY (id_receta),
    CONSTRAINT uq_receta_consulta     UNIQUE (id_consulta),
    CONSTRAINT uq_receta_cita_proxima UNIQUE (id_cita_proxima),
    CONSTRAINT fk_receta_consulta FOREIGN KEY (id_consulta)
        REFERENCES consulta (id_consulta) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_receta_cita_proxima FOREIGN KEY (id_cita_proxima)
        REFERENCES cita (id_cita) ON DELETE SET NULL ON UPDATE CASCADE
);

-- Medicamentos prescritos en la receta con posología y duración del tratamiento.
CREATE TABLE receta_detalle (
    id_receta_detalle BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_receta         BIGINT       NOT NULL,
    id_medicamento    INTEGER      NOT NULL,
    dosis             VARCHAR(100) NOT NULL,
    duracion_dias     SMALLINT     NOT NULL,
    CONSTRAINT pk_receta_detalle   PRIMARY KEY (id_receta_detalle),
    CONSTRAINT uq_receta_detalle   UNIQUE (id_receta, id_medicamento),
    CONSTRAINT ck_receta_dosis     CHECK (length(trim(dosis)) >= 2),  -- posologia y dosis especificada
    CONSTRAINT ck_receta_duracion  CHECK (duracion_dias > 0),  -- periodo de tratamiento mayor a cero dias
    CONSTRAINT fk_recdet_receta FOREIGN KEY (id_receta)
        REFERENCES receta (id_receta) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_recdet_medicamento FOREIGN KEY (id_medicamento)
        REFERENCES medicamento (id_medicamento) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Orden médica de exámenes diagnósticos de laboratorio expedida en consulta.
CREATE TABLE orden_laboratorio (
    id_orden_laboratorio BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_consulta          BIGINT NOT NULL,
    fecha_emision        DATE   NOT NULL DEFAULT CURRENT_DATE,
    indicaciones         TEXT,
    CONSTRAINT pk_orden_laboratorio PRIMARY KEY (id_orden_laboratorio),
    CONSTRAINT fk_orden_consulta FOREIGN KEY (id_consulta)
        REFERENCES consulta (id_consulta) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Exámenes específicos prescritos en la orden de laboratorio (N:M).
CREATE TABLE orden_laboratorio_detalle (
    id_orden_laboratorio BIGINT  NOT NULL,
    id_examen            INTEGER NOT NULL,
    CONSTRAINT pk_orden_laboratorio_detalle PRIMARY KEY (id_orden_laboratorio, id_examen),
    CONSTRAINT fk_ordendet_orden FOREIGN KEY (id_orden_laboratorio)
        REFERENCES orden_laboratorio (id_orden_laboratorio) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_ordendet_examen FOREIGN KEY (id_examen)
        REFERENCES examen_laboratorio (id_examen) ON DELETE RESTRICT ON UPDATE CASCADE
);


/* ============================================================================
   M6. CIRUGÍA: PROCESO QUIRÚRGICO Y CHECKLISTS (14 TABLAS)
   ============================================================================ */

-- Historia clínica preoperatoria que documenta interrogatorio y exploración física.
CREATE TABLE historia_clinica (
    id_historia_clinica                    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_episodio                            BIGINT      NOT NULL,
    id_medico                              INTEGER     NOT NULL,
    fecha_hora                             TIMESTAMPTZ NOT NULL DEFAULT now(),
    tipo_interrogatorio                    VARCHAR(10) NOT NULL,
    informante                             VARCHAR(120),
    antecedentes_heredofamiliares          TEXT,
    antecedentes_personales_no_patologicos TEXT,
    antecedentes_patologicos               TEXT,
    padecimiento_actual                    TEXT        NOT NULL,
    interrogatorio_aparatos_sistemas       TEXT,
    sintomas_generales_terapeutica         TEXT,
    estudios_previos                       TEXT,
    id_signos_vitales                      BIGINT,
    exploracion_general                    TEXT,
    explo_cabeza                           TEXT,
    explo_cuello                           TEXT,
    explo_torax                            TEXT,
    explo_abdomen                          TEXT,
    explo_extremidades                     TEXT,
    explo_columna_vertebral                TEXT,
    explo_cavidad_bucal                    TEXT,
    explo_cavidad_vaginal                  TEXT,
    explo_cavidad_rectal                   TEXT,
    explo_conducto_auditivo_externo        TEXT,
    CONSTRAINT pk_historia_clinica     PRIMARY KEY (id_historia_clinica),
    CONSTRAINT uq_historia_signos      UNIQUE (id_signos_vitales),
    CONSTRAINT ck_historia_interrog    CHECK (tipo_interrogatorio IN ('Directo', 'Indirecto')),  -- modalidad del interrogatorio clinico
    CONSTRAINT ck_historia_informante  CHECK ((tipo_interrogatorio = 'Indirecto' AND informante IS NOT NULL) OR (tipo_interrogatorio = 'Directo' AND informante IS NULL)),  -- informante obligatorio exclusivamente en anamnesis indirecta
    CONSTRAINT ck_historia_padecimiento CHECK (length(trim(padecimiento_actual)) >= 5),  -- descripcion detallada del cuadro patologico
    CONSTRAINT fk_historia_episodio FOREIGN KEY (id_episodio)
        REFERENCES episodio (id_episodio) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_historia_medico FOREIGN KEY (id_medico)
        REFERENCES medico (id_personal) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_historia_signos FOREIGN KEY (id_signos_vitales)
        REFERENCES registro_signos_vitales (id_signos_vitales) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Solicitud de agendamiento quirúrgico formalizada por el cirujano.
CREATE TABLE solicitud_cirugia (
    id_solicitud_cirugia BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_episodio          BIGINT      NOT NULL,
    id_historia_clinica  BIGINT      NOT NULL,
    id_cirujano          INTEGER     NOT NULL,
    caracter             VARCHAR(10) NOT NULL,
    id_tipo_anestesia    INTEGER     NOT NULL,
    tiempo_estimado_min  SMALLINT    NOT NULL,
    fecha_hora_solicitud TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_solicitud_cirugia PRIMARY KEY (id_solicitud_cirugia),
    CONSTRAINT ck_solicitud_caracter CHECK (caracter IN ('Urgente', 'Programado')),  -- prioridad quirurgica urgente o electiva programada
    CONSTRAINT ck_solicitud_tiempo   CHECK (tiempo_estimado_min BETWEEN 15 AND 1440),  -- duracion quirurgica estimada entre 15 minutos y 24 horas
    CONSTRAINT fk_solicitud_episodio FOREIGN KEY (id_episodio)
        REFERENCES episodio (id_episodio) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_solicitud_historia FOREIGN KEY (id_historia_clinica)
        REFERENCES historia_clinica (id_historia_clinica) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_solicitud_cirujano FOREIGN KEY (id_cirujano)
        REFERENCES medico (id_personal) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_solicitud_anestesia FOREIGN KEY (id_tipo_anestesia)
        REFERENCES tipo_anestesia (id_tipo_anestesia) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Procedimientos quirúrgicos solicitados para la intervención (N:M).
CREATE TABLE solicitud_procedimiento (
    id_solicitud_cirugia BIGINT  NOT NULL,
    id_procedimiento     INTEGER NOT NULL,
    CONSTRAINT pk_solicitud_procedimiento PRIMARY KEY (id_solicitud_cirugia, id_procedimiento),
    CONSTRAINT fk_solproc_solicitud FOREIGN KEY (id_solicitud_cirugia)
        REFERENCES solicitud_cirugia (id_solicitud_cirugia) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_solproc_procedimiento FOREIGN KEY (id_procedimiento)
        REFERENCES procedimiento_quirurgico (id_procedimiento) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Insumos consumibles requeridos para la cirugía con cantidad (N:M).
CREATE TABLE solicitud_insumo (
    id_solicitud_cirugia BIGINT  NOT NULL,
    id_insumo            INTEGER NOT NULL,
    cantidad             INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT pk_solicitud_insumo   PRIMARY KEY (id_solicitud_cirugia, id_insumo),
    CONSTRAINT ck_solinsumo_cantidad CHECK (cantidad > 0),  -- cantidad solicitada mayor a cero
    CONSTRAINT fk_solins_solicitud FOREIGN KEY (id_solicitud_cirugia)
        REFERENCES solicitud_cirugia (id_solicitud_cirugia) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_solins_insumo FOREIGN KEY (id_insumo)
        REFERENCES insumo (id_insumo) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Instrumental quirúrgico requerido para la cirugía con cantidad (N:M).
CREATE TABLE solicitud_instrumento (
    id_solicitud_cirugia BIGINT  NOT NULL,
    id_instrumento       INTEGER NOT NULL,
    cantidad             INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT pk_solicitud_instrumento PRIMARY KEY (id_solicitud_cirugia, id_instrumento),
    CONSTRAINT ck_solinstr_cantidad     CHECK (cantidad > 0),  -- cantidad requerida mayor a cero
    CONSTRAINT fk_solinstr_solicitud FOREIGN KEY (id_solicitud_cirugia)
        REFERENCES solicitud_cirugia (id_solicitud_cirugia) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_solinstr_instrumento FOREIGN KEY (id_instrumento)
        REFERENCES instrumento (id_instrumento) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Equipos biomédicos solicitados para la intervención con cantidad (N:M).
CREATE TABLE solicitud_equipo (
    id_solicitud_cirugia BIGINT  NOT NULL,
    id_equipo            INTEGER NOT NULL,
    cantidad             INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT pk_solicitud_equipo PRIMARY KEY (id_solicitud_cirugia, id_equipo),
    CONSTRAINT ck_soleq_cantidad   CHECK (cantidad > 0),  -- cantidad requerida mayor a cero
    CONSTRAINT fk_soleq_solicitud FOREIGN KEY (id_solicitud_cirugia)
        REFERENCES solicitud_cirugia (id_solicitud_cirugia) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_soleq_equipo FOREIGN KEY (id_equipo)
        REFERENCES equipo (id_equipo) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Dictamen formal de revisión médica que aprueba o rechaza la solicitud de cirugía.
CREATE TABLE revision_solicitud (
    id_revision          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_solicitud_cirugia BIGINT       NOT NULL,
    decision             VARCHAR(10)  NOT NULL,
    fecha_hora           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    razones              VARCHAR(500),
    CONSTRAINT pk_revision_solicitud  PRIMARY KEY (id_revision),
    CONSTRAINT uq_revision_solicitud  UNIQUE (id_solicitud_cirugia),
    CONSTRAINT ck_revision_decision   CHECK (decision IN ('Aprobada', 'Rechazada')),  -- dictamen oficial del comite
    CONSTRAINT ck_revision_razones    CHECK ((decision = 'Rechazada' AND razones IS NOT NULL) OR (decision = 'Aprobada')),  -- motivo justificado mandatorio en caso de rechazo
    CONSTRAINT fk_revision_solicitud FOREIGN KEY (id_solicitud_cirugia)
        REFERENCES solicitud_cirugia (id_solicitud_cirugia) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Médicos especialistas miembros del comité que dictaminaron la solicitud (N:M).
CREATE TABLE revision_miembro_comite (
    id_revision BIGINT  NOT NULL,
    id_medico   INTEGER NOT NULL,
    CONSTRAINT pk_revision_miembro_comite PRIMARY KEY (id_revision, id_medico),
    CONSTRAINT fk_revmiem_revision FOREIGN KEY (id_revision)
        REFERENCES revision_solicitud (id_revision) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_revmiem_medico FOREIGN KEY (id_medico)
        REFERENCES medico (id_personal) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Cirugía programada o ejecutada en quirófano con control de tiempos y no traslape.
CREATE TABLE cirugia (
    id_cirugia           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_solicitud_cirugia BIGINT      NOT NULL,
    id_quirofano         INTEGER     NOT NULL,
    inicio_programado    TIMESTAMPTZ NOT NULL,
    fin_programado       TIMESTAMPTZ NOT NULL,
    inicio_real          TIMESTAMPTZ,
    fin_real             TIMESTAMPTZ,
    estado               VARCHAR(10) NOT NULL DEFAULT 'Programada',
    id_ingreso           BIGINT,
    condicion_evolucion  VARCHAR(20),
    CONSTRAINT pk_cirugia              PRIMARY KEY (id_cirugia),
    CONSTRAINT uq_cirugia_solicitud    UNIQUE (id_solicitud_cirugia),
    CONSTRAINT ck_cirugia_estado       CHECK (estado IN ('Programada', 'En curso', 'Finalizada', 'Cancelada')),  -- ciclo de estado de la operacion
    CONSTRAINT ck_cirugia_programada   CHECK (fin_programado > inicio_programado),  -- fin programado cronologicamente posterior al inicio
    CONSTRAINT ck_cirugia_real         CHECK (fin_real IS NULL OR (inicio_real IS NOT NULL AND fin_real > inicio_real)),  -- fin real coherente con inicio real registrado
    CONSTRAINT ck_cirugia_evolucion    CHECK (condicion_evolucion IS NULL OR condicion_evolucion IN ('Sin complicaciones', 'Complicaciones', 'Complicaciones graves')),  -- condiciones de evolucion del acto quirurgico
    CONSTRAINT ck_cirugia_evolucion_est CHECK (condicion_evolucion IS NULL OR estado = 'Finalizada'),  -- evolucion transitoria consignable exclusivamente al finalizar
    -- Restricción de exclusión GiST: impide solapes de cirugías activas en el mismo quirófano
    CONSTRAINT ex_cirugia_traslape     EXCLUDE USING gist (
        id_quirofano WITH =,
        (tstzrange(inicio_programado, fin_programado)) WITH &&
    ) WHERE (estado <> 'Cancelada'),  -- exclusion de solapes temporales por quirofano
    CONSTRAINT fk_cirugia_solicitud FOREIGN KEY (id_solicitud_cirugia)
        REFERENCES solicitud_cirugia (id_solicitud_cirugia) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_cirugia_quirofano FOREIGN KEY (id_quirofano)
        REFERENCES espacio_atencion (id_espacio) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_cirugia_ingreso FOREIGN KEY (id_ingreso)
        REFERENCES ingreso (id_ingreso) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Equipo de profesionales de la salud participante en la intervención y su rol.
CREATE TABLE cirugia_equipo_medico (
    id_cirugia  BIGINT      NOT NULL,
    id_personal INTEGER     NOT NULL,
    rol         VARCHAR(30) NOT NULL,
    CONSTRAINT pk_cirugia_equipo_medico PRIMARY KEY (id_cirugia, id_personal),
    CONSTRAINT ck_cirugia_equipo_rol    CHECK (rol IN ('Cirujano principal', 'Cirujano ayudante', 'Anestesiologo', 'Enfermero instrumentista', 'Enfermero circulante', 'Practicante de medicina', 'Practicante de enfermeria')),  -- roles acreditados en quirofano
    CONSTRAINT fk_cireq_cirugia FOREIGN KEY (id_cirugia)
        REFERENCES cirugia (id_cirugia) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_cireq_personal FOREIGN KEY (id_personal)
        REFERENCES personal (id_personal) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Registro y verificación de consentimiento informado firmado para la cirugía.
CREATE TABLE consentimiento_informado (
    id_consentimiento             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_cirugia                    BIGINT       NOT NULL,
    nombre_procedimiento          VARCHAR(200) NOT NULL,
    objetivo_procedimiento        TEXT         NOT NULL,
    caracteristicas_procedimiento TEXT         NOT NULL,
    riesgos_procedimiento         TEXT         NOT NULL,
    id_medico                     INTEGER      NOT NULL,
    firmado_por_medico            BOOLEAN      NOT NULL DEFAULT FALSE,
    firmante_tipo                 VARCHAR(20)  NOT NULL,
    id_paciente_encargado         INTEGER,
    firmado_por_firmante          BOOLEAN      NOT NULL DEFAULT FALSE,
    fecha_obtencion               TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_consentimiento_informado PRIMARY KEY (id_consentimiento),
    CONSTRAINT uq_consentimiento_cirugia   UNIQUE (id_cirugia),
    CONSTRAINT ck_consentimiento_firmante  CHECK (firmante_tipo IN ('Paciente', 'Familiar', 'Tutor', 'Representante legal')),  -- personeria del otorgante del consentimiento
    CONSTRAINT ck_consentimiento_encargado CHECK ((firmante_tipo = 'Paciente' AND id_paciente_encargado IS NULL) OR (firmante_tipo <> 'Paciente' AND id_paciente_encargado IS NOT NULL)),  -- encargado identificado obligatoriamente cuando no firma el propio paciente
    CONSTRAINT fk_consent_cirugia FOREIGN KEY (id_cirugia)
        REFERENCES cirugia (id_cirugia) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_consent_medico FOREIGN KEY (id_medico)
        REFERENCES medico (id_personal) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_consent_encargado FOREIGN KEY (id_paciente_encargado)
        REFERENCES paciente_encargado (id_paciente_encargado) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Chequeo y valoración preanestésica de la cirugía con estratificación ASA.
CREATE TABLE evaluacion_preanestesica (
    id_evaluacion            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_cirugia               BIGINT      NOT NULL,
    clasificacion_asa        SMALLINT    NOT NULL,
    id_medico_clasifica      INTEGER     NOT NULL,
    firmado_medico_clasifica BOOLEAN     NOT NULL DEFAULT FALSE,
    plan_anestesia           TEXT        NOT NULL,
    id_anestesiologo         INTEGER     NOT NULL,
    fecha_hora               TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_evaluacion_preanestesica PRIMARY KEY (id_evaluacion),
    CONSTRAINT uq_evaluacion_cirugia       UNIQUE (id_cirugia),
    CONSTRAINT ck_evaluacion_asa           CHECK (clasificacion_asa BETWEEN 1 AND 6),  -- escala ASA del 1 (paciente sano) al 6 (muerte cerebral)
    CONSTRAINT ck_evaluacion_plan          CHECK (length(trim(plan_anestesia)) >= 5),  -- plan de manejo anestesico detallado
    CONSTRAINT fk_evalpre_cirugia FOREIGN KEY (id_cirugia)
        REFERENCES cirugia (id_cirugia) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_evalpre_clasifica FOREIGN KEY (id_medico_clasifica)
        REFERENCES medico (id_personal) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_evalpre_anestesiologo FOREIGN KEY (id_anestesiologo)
        REFERENCES medico (id_personal) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Registro de cada ítem de lista de verificación quirúrgica con enfermero y hora.
CREATE TABLE cirugia_verificacion (
    id_verificacion     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_cirugia          BIGINT       NOT NULL,
    id_item             INTEGER      NOT NULL,
    resultado           VARCHAR(25)  NOT NULL,
    detalle             VARCHAR(500),
    fecha_hora_registro TIMESTAMPTZ  NOT NULL DEFAULT now(),
    id_enfermero        INTEGER      NOT NULL,
    CONSTRAINT pk_cirugia_verificacion PRIMARY KEY (id_verificacion),
    CONSTRAINT uq_cirugia_verificacion UNIQUE (id_cirugia, id_item),
    CONSTRAINT ck_verificacion_res     CHECK (resultado IN ('Exito', 'Fallo', 'Aceptable', 'Medianamente aceptable', 'No aceptable')),  -- resultado valido segun el tipo de escala evaluada
    CONSTRAINT fk_cirver_cirugia FOREIGN KEY (id_cirugia)
        REFERENCES cirugia (id_cirugia) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_cirver_item FOREIGN KEY (id_item)
        REFERENCES item_verificacion (id_item) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_cirver_enfermero FOREIGN KEY (id_enfermero)
        REFERENCES personal (id_personal) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Documento de cierre por cada fase quirúrgica remitido a secretaría del hospital.
CREATE TABLE cirugia_documento_fase (
    id_documento           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_cirugia             BIGINT      NOT NULL,
    fase                   VARCHAR(15) NOT NULL,
    id_enfermero           INTEGER     NOT NULL,
    fecha_envio_secretaria DATE        NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT pk_cirugia_documento_fase PRIMARY KEY (id_documento),
    CONSTRAINT uq_cirugia_documento_fase UNIQUE (id_cirugia, fase),
    CONSTRAINT ck_documento_fase         CHECK (fase IN ('Preoperatorio', 'Intraoperatorio', 'Postoperatorio')),  -- fase quirurgica formalmente documentada
    CONSTRAINT fk_cirdoc_cirugia FOREIGN KEY (id_cirugia)
        REFERENCES cirugia (id_cirugia) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_cirdoc_enfermero FOREIGN KEY (id_enfermero)
        REFERENCES personal (id_personal) ON DELETE RESTRICT ON UPDATE CASCADE
);


/* ============================================================================
   M7. FACTURACIÓN Y PAGOS (6 TABLAS)
   ============================================================================ */

-- Arancel hospitalario de atención médica y costo por día de internamiento.
CREATE TABLE tarifa_servicio (
    id_hospital    INTEGER       NOT NULL,
    id_servicio    INTEGER       NOT NULL,
    costo_atencion NUMERIC(12,2) NOT NULL,
    costo_dia      NUMERIC(12,2),
    CONSTRAINT pk_tarifa_servicio     PRIMARY KEY (id_hospital, id_servicio),
    CONSTRAINT ck_tarifa_serv_atenc   CHECK (costo_atencion >= 0),  -- arancel de atencion médica no negativo
    CONSTRAINT ck_tarifa_serv_dia     CHECK (costo_dia IS NULL OR costo_dia >= 0),  -- costo de estancia por dia no negativo
    CONSTRAINT fk_tarserv_hospital FOREIGN KEY (id_hospital)
        REFERENCES hospital (id_hospital) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_tarserv_servicio FOREIGN KEY (id_servicio)
        REFERENCES servicio_medico (id_servicio) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Arancel institucional por procedimiento quirúrgico fijado por cada hospital.
CREATE TABLE tarifa_procedimiento (
    id_hospital      INTEGER       NOT NULL,
    id_procedimiento INTEGER       NOT NULL,
    costo            NUMERIC(12,2) NOT NULL,
    CONSTRAINT pk_tarifa_procedimiento PRIMARY KEY (id_hospital, id_procedimiento),
    CONSTRAINT ck_tarifa_proc_costo    CHECK (costo >= 0),  -- honorario o costo quirurgico no negativo
    CONSTRAINT fk_tarproc_hospital FOREIGN KEY (id_hospital)
        REFERENCES hospital (id_hospital) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_tarproc_procedimiento FOREIGN KEY (id_procedimiento)
        REFERENCES procedimiento_quirurgico (id_procedimiento) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Precio unitario de insumos y consumibles médicos fijado por hospital.
CREATE TABLE tarifa_insumo (
    id_hospital     INTEGER       NOT NULL,
    id_insumo       INTEGER       NOT NULL,
    precio_unitario NUMERIC(12,2) NOT NULL,
    CONSTRAINT pk_tarifa_insumo     PRIMARY KEY (id_hospital, id_insumo),
    CONSTRAINT ck_tarifa_ins_precio CHECK (precio_unitario >= 0),  -- precio unitario de venta no negativo
    CONSTRAINT fk_tarins_hospital FOREIGN KEY (id_hospital)
        REFERENCES hospital (id_hospital) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_tarins_insumo FOREIGN KEY (id_insumo)
        REFERENCES insumo (id_insumo) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Factura contable emitida al liquidar los servicios de un episodio asistencial.
CREATE TABLE factura (
    id_factura        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    serie             VARCHAR(10)  NOT NULL DEFAULT 'A',
    numero_factura    VARCHAR(20)  NOT NULL,
    id_episodio       BIGINT       NOT NULL,
    fecha_emision     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    nit_cliente       VARCHAR(15)  NOT NULL DEFAULT 'CF',
    nombre_cliente    VARCHAR(150) NOT NULL,
    descripcion       VARCHAR(300) NOT NULL,
    numero_cuotas     SMALLINT     NOT NULL DEFAULT 1,
    id_personal_emite INTEGER      NOT NULL,
    estado            VARCHAR(10)  NOT NULL DEFAULT 'Emitida',
    CONSTRAINT pk_factura          PRIMARY KEY (id_factura),
    CONSTRAINT uq_factura_numero   UNIQUE (serie, numero_factura),
    CONSTRAINT ck_factura_cuotas   CHECK (numero_cuotas BETWEEN 1 AND 12),  -- plan de financiamiento desde pago unico hasta 12 mensualidades
    CONSTRAINT ck_factura_estado   CHECK (estado IN ('Emitida', 'Anulada')),  -- estado contable del comprobante
    CONSTRAINT ck_factura_desc     CHECK (length(trim(descripcion)) >= 5),  -- descripcion clara de los servicios brindados
    CONSTRAINT fk_factura_episodio FOREIGN KEY (id_episodio)
        REFERENCES episodio (id_episodio) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_factura_personal FOREIGN KEY (id_personal_emite)
        REFERENCES personal (id_personal) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Renglones y conceptos facturados detallando cantidad, precio y porcentaje.
CREATE TABLE factura_detalle (
    id_factura_detalle  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_factura          BIGINT        NOT NULL,
    concepto            VARCHAR(25)   NOT NULL,
    descripcion         VARCHAR(200)  NOT NULL,
    cantidad            NUMERIC(10,2) NOT NULL DEFAULT 1,
    precio_unitario     NUMERIC(12,2) NOT NULL,
    porcentaje_aplicado NUMERIC(5,2)  NOT NULL DEFAULT 100,
    id_consulta         BIGINT,
    id_ingreso          BIGINT,
    id_cirugia          BIGINT,
    CONSTRAINT pk_factura_detalle   PRIMARY KEY (id_factura_detalle),
    CONSTRAINT ck_facdet_concepto   CHECK (concepto IN ('Consulta', 'Emergencia', 'Cirugia', 'Hospitalizacion', 'Dias de internamiento', 'Insumos', 'Otro')),  -- concepto asistencial facturado
    CONSTRAINT ck_facdet_cantidad   CHECK (cantidad > 0),  -- volumen o unidades facturadas mayores a cero
    CONSTRAINT ck_facdet_precio     CHECK (precio_unitario >= 0),  -- precio unitario base no negativo
    CONSTRAINT ck_facdet_porcentaje CHECK (porcentaje_aplicado BETWEEN 0 AND 200),  -- factor porcentual aplicado (descuentos 75/80 o recargo 110)
    CONSTRAINT ck_facdet_origen     CHECK (num_nonnulls(id_consulta, id_ingreso, id_cirugia) <= 1),  -- a lo sumo un vinculo de origen clinico por renglon
    CONSTRAINT fk_facdet_factura FOREIGN KEY (id_factura)
        REFERENCES factura (id_factura) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_facdet_consulta FOREIGN KEY (id_consulta)
        REFERENCES consulta (id_consulta) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_facdet_ingreso FOREIGN KEY (id_ingreso)
        REFERENCES ingreso (id_ingreso) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_facdet_cirugia FOREIGN KEY (id_cirugia)
        REFERENCES cirugia (id_cirugia) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Registro de amortizaciones y cobro de cuotas en las cajas del hospital.
CREATE TABLE pago (
    id_pago            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_factura         BIGINT        NOT NULL,
    numero_cuota       SMALLINT      NOT NULL,
    monto              NUMERIC(12,2) NOT NULL,
    fecha_pago         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    id_metodo_pago     INTEGER       NOT NULL,
    id_unidad_hospital INTEGER       NOT NULL,
    id_personal_recibe INTEGER       NOT NULL,
    referencia         VARCHAR(50),
    CONSTRAINT pk_pago         PRIMARY KEY (id_pago),
    CONSTRAINT uq_pago_cuota   UNIQUE (id_factura, numero_cuota),
    CONSTRAINT ck_pago_cuota   CHECK (numero_cuota BETWEEN 1 AND 12),  -- cuota mensual dentro del limite del 1 al 12
    CONSTRAINT ck_pago_monto   CHECK (monto > 0),  -- abono o cancelacion en efectivo mayor a cero
    CONSTRAINT fk_pago_factura FOREIGN KEY (id_factura)
        REFERENCES factura (id_factura) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_pago_metodo FOREIGN KEY (id_metodo_pago)
        REFERENCES metodo_pago (id_metodo_pago) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_pago_unidad FOREIGN KEY (id_unidad_hospital)
        REFERENCES unidad_hospital (id_unidad_hospital) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_pago_personal FOREIGN KEY (id_personal_recibe)
        REFERENCES personal (id_personal) ON DELETE RESTRICT ON UPDATE CASCADE
);


/* ============================================================================
   M8. CALIDAD DEL SERVICIO (2 TABLAS)
   ============================================================================ */

-- Calificación de la calidad del servicio brindado por el hospital evaluado por episodio.
CREATE TABLE calificacion_hospital (
    id_calificacion_hospital BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_episodio              BIGINT       NOT NULL,
    puntuacion               SMALLINT     NOT NULL,
    comentario               VARCHAR(500),
    fecha_hora               TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_calificacion_hospital PRIMARY KEY (id_calificacion_hospital),
    CONSTRAINT uq_calificacion_hospital UNIQUE (id_episodio),
    CONSTRAINT ck_calhosp_puntuacion    CHECK (puntuacion BETWEEN 1 AND 5),  -- escala de satisfaccion del 1 al 5
    CONSTRAINT fk_calhosp_episodio FOREIGN KEY (id_episodio)
        REFERENCES episodio (id_episodio) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Calificación individualizada de médicos, enfermeros o encargados de recepción.
CREATE TABLE calificacion_personal (
    id_calificacion_personal BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_episodio              BIGINT       NOT NULL,
    id_personal              INTEGER      NOT NULL,
    puntuacion               SMALLINT     NOT NULL,
    comentario               VARCHAR(500),
    fecha_hora               TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_calificacion_personal PRIMARY KEY (id_calificacion_personal),
    CONSTRAINT uq_calificacion_personal UNIQUE (id_episodio, id_personal),
    CONSTRAINT ck_calpers_puntuacion    CHECK (puntuacion BETWEEN 1 AND 5),  -- escala de desempeno profesional del 1 al 5
    CONSTRAINT fk_calpers_episodio FOREIGN KEY (id_episodio)
        REFERENCES episodio (id_episodio) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_calpers_personal FOREIGN KEY (id_personal)
        REFERENCES personal (id_personal) ON DELETE RESTRICT ON UPDATE CASCADE
);


/* ============================================================================
   ÍNDICES DE RENDIMIENTO (B-TREE Y REGLAS DE NEGOCIO PARCIALES)
   ============================================================================ */

-- Reglas de unicidad parcial de negocio
CREATE UNIQUE INDEX uq_paciente_encargado_principal ON paciente_encargado (id_paciente) WHERE es_principal;
CREATE UNIQUE INDEX uq_medico_especialidad_principal ON medico_especialidad (id_medico) WHERE es_principal;
CREATE UNIQUE INDEX uq_cita_medico_horario          ON cita (id_medico, fecha_hora) WHERE estado IN ('Programada', 'Realizada');
CREATE UNIQUE INDEX uq_factura_episodio_emitida      ON factura (id_episodio) WHERE estado = 'Emitida';
CREATE UNIQUE INDEX uq_cirugia_cirujano_principal   ON cirugia_equipo_medico (id_cirugia) WHERE rol = 'Cirujano principal';

-- Cobertura de llaves foráneas para evitar escaneos secuenciales (Sequential Scans) y bloqueos
CREATE INDEX ix_municipio_departamento      ON municipio (id_departamento);
CREATE INDEX ix_direccion_municipio         ON direccion (id_municipio);
CREATE INDEX ix_servicio_tipo_unidad        ON servicio_medico (id_tipo_unidad);
CREATE INDEX ix_proc_especialidad           ON procedimiento_quirurgico (id_especialidad);
CREATE INDEX ix_item_verif_momento          ON item_verificacion (id_momento);
CREATE INDEX ix_hospital_direccion          ON hospital (id_direccion);
CREATE INDEX ix_unidad_hosp_hospital        ON unidad_hospital (id_hospital);
CREATE INDEX ix_unidad_hosp_tipo            ON unidad_hospital (id_tipo_unidad);
CREATE INDEX ix_espacio_unidad              ON espacio_atencion (id_unidad_hospital);
CREATE INDEX ix_clinica_hospital            ON clinica (id_hospital);
CREATE INDEX ix_persona_direccion           ON persona (id_direccion);
CREATE INDEX ix_persona_apellidos           ON persona (apellidos, nombres);
CREATE INDEX ix_persona_dpi                 ON persona (dpi);
CREATE INDEX ix_paciente_persona            ON paciente (id_persona);
CREATE INDEX ix_paciente_encargado_pers     ON paciente_encargado (id_persona);
CREATE INDEX ix_personal_persona            ON personal (id_persona);
CREATE INDEX ix_personal_tipo               ON personal (tipo_personal);
CREATE INDEX ix_medesp_especialidad         ON medico_especialidad (id_especialidad);
CREATE INDEX ix_asignacion_personal         ON asignacion_personal (id_personal);
CREATE INDEX ix_asignacion_unidad           ON asignacion_personal (id_unidad_hospital);
CREATE INDEX ix_horario_clinica             ON horario_medico (id_clinica);
CREATE INDEX ix_episodio_paciente           ON episodio (id_paciente, fecha_apertura);
CREATE INDEX ix_episodio_hospital           ON episodio (id_hospital, fecha_apertura);
CREATE INDEX ix_signos_episodio             ON registro_signos_vitales (id_episodio, fecha_hora);
CREATE INDEX ix_ingreso_episodio            ON ingreso (id_episodio);
CREATE INDEX ix_ingreso_unidad_fecha        ON ingreso (id_unidad_hospital, fecha_hora_ingreso);
CREATE INDEX ix_ingreso_espacio             ON ingreso (id_espacio);
CREATE INDEX ix_ingreso_medico              ON ingreso (id_medico);
CREATE INDEX ix_ingreso_diagnostico         ON ingreso (id_diagnostico_presuntivo);
CREATE INDEX ix_traslado_episodio           ON traslado (id_episodio);
CREATE INDEX ix_traslado_origen             ON traslado (id_hospital_origen, id_tipo_unidad_origen);
CREATE INDEX ix_traslado_destino            ON traslado (id_hospital_destino, id_tipo_unidad_destino);
CREATE INDEX ix_egreso_medico               ON egreso (id_medico);
CREATE INDEX ix_egreso_fecha                ON egreso (fecha_hora_egreso);
CREATE INDEX ix_egdiag_diagnostico          ON egreso_diagnostico_secundario (id_diagnostico);
CREATE INDEX ix_consumo_ingreso             ON consumo_insumo (id_ingreso);
CREATE INDEX ix_consumo_insumo              ON consumo_insumo (id_insumo);
CREATE INDEX ix_cita_paciente               ON cita (id_paciente, fecha_hora);
CREATE INDEX ix_cita_clinica_fecha          ON cita (id_clinica, fecha_hora);
CREATE INDEX ix_consulta_episodio           ON consulta (id_episodio);
CREATE INDEX ix_receta_detalle_med          ON receta_detalle (id_medicamento);
CREATE INDEX ix_orden_lab_consulta          ON orden_laboratorio (id_consulta);
CREATE INDEX ix_orden_lab_det_examen        ON orden_laboratorio_detalle (id_examen);
CREATE INDEX ix_historia_episodio           ON historia_clinica (id_episodio);
CREATE INDEX ix_solicitud_episodio          ON solicitud_cirugia (id_episodio);
CREATE INDEX ix_solicitud_cirujano          ON solicitud_cirugia (id_cirujano);
CREATE INDEX ix_solproc_procedimiento       ON solicitud_procedimiento (id_procedimiento);
CREATE INDEX ix_cirugia_quirofano           ON cirugia (id_quirofano);
CREATE INDEX ix_cirugia_estado_inicio       ON cirugia (estado, inicio_programado);
CREATE INDEX ix_cireq_personal              ON cirugia_equipo_medico (id_personal);
CREATE INDEX ix_cirver_enfermero            ON cirugia_verificacion (id_enfermero);
CREATE INDEX ix_factura_detalle_factura     ON factura_detalle (id_factura);
CREATE INDEX ix_pago_factura                ON pago (id_factura);
CREATE INDEX ix_pago_fecha                  ON pago (fecha_pago);
CREATE INDEX ix_calpers_personal            ON calificacion_personal (id_personal);


/* ============================================================================
   VISTAS DE NEGOCIO Y DERIVACIÓN (ESTRICTO CUMPLIMIENTO 3FN)
   ============================================================================ */

-- Vista analítica de pacientes con cálculo dinámico de edad en años cumplidos.
CREATE OR REPLACE VIEW vw_paciente AS
SELECT 
    pa.id_paciente,
    pa.no_expediente,
    pe.nombres,
    pe.apellidos,
    pe.dpi,
    pe.sexo,
    pe.fecha_nacimiento,
    EXTRACT(YEAR FROM age(CURRENT_DATE, pe.fecha_nacimiento))::INTEGER AS edad_anios,
    pa.estado_civil,
    pe.telefono,
    di.area,
    di.detalle AS direccion_completa,
    mu.nombre AS municipio,
    de.nombre AS departamento
FROM paciente pa
JOIN persona      pe ON pe.id_persona      = pa.id_persona
JOIN direccion    di ON di.id_direccion    = pe.id_direccion
JOIN municipio    mu ON mu.id_municipio    = di.id_municipio
JOIN departamento de ON de.id_departamento = mu.id_departamento;

-- Cálculo de días de internamiento por egreso (mínimo 1 día para fines tarifarios).
CREATE OR REPLACE VIEW vw_egreso_dias AS
SELECT 
    eg.id_egreso,
    ing.id_ingreso,
    ing.id_episodio,
    tu.nombre AS unidad,
    ing.fecha_hora_ingreso,
    eg.fecha_hora_egreso,
    GREATEST(1, CEIL(EXTRACT(EPOCH FROM (eg.fecha_hora_egreso - ing.fecha_hora_ingreso)) / 86400))::INTEGER AS dias_hospitalizado
FROM egreso eg
JOIN ingreso         ing ON ing.id_ingreso        = eg.id_ingreso
JOIN unidad_hospital uh  ON uh.id_unidad_hospital = ing.id_unidad_hospital
JOIN tipo_unidad     tu  ON tu.id_tipo_unidad     = uh.id_tipo_unidad;

-- Estado financiero de facturas con total facturado, total amortizado y saldo insoluto.
CREATE OR REPLACE VIEW vw_factura_resumen AS
SELECT 
    f.id_factura,
    f.serie,
    f.numero_factura,
    f.id_episodio,
    f.numero_cuotas,
    f.estado,
    COALESCE(t.total, 0.00)                                   AS total_facturado,
    COALESCE(p.pagado, 0.00)                                  AS total_pagado,
    ROUND(COALESCE(t.total, 0.00) - COALESCE(p.pagado, 0.00), 2) AS saldo_pendiente
FROM factura f
LEFT JOIN (
    SELECT 
        id_factura,
        ROUND(SUM(cantidad * precio_unitario * (porcentaje_aplicado / 100.0)), 2) AS total
    FROM factura_detalle
    GROUP BY id_factura
) t ON t.id_factura = f.id_factura
LEFT JOIN (
    SELECT 
        id_factura,
        ROUND(SUM(monto), 2) AS pagado
    FROM pago
    GROUP BY id_factura
) p ON p.id_factura = f.id_factura;

-- Reporte de cirugías rechazadas por el comité médico con facultativo y justificación.
CREATE OR REPLACE VIEW vw_cirugias_rechazadas AS
SELECT 
    r.id_revision,
    s.id_solicitud_cirugia,
    s.id_episodio,
    ep.id_paciente,
    s.id_cirujano,
    pe.nombres || ' ' || pe.apellidos AS cirujano,
    s.caracter,
    r.fecha_hora                      AS fecha_revision,
    r.razones                         AS motivo_rechazo
FROM revision_solicitud r
JOIN solicitud_cirugia s  ON s.id_solicitud_cirugia = r.id_solicitud_cirugia
JOIN episodio         ep  ON ep.id_episodio         = s.id_episodio
JOIN personal         pl  ON pl.id_personal         = s.id_cirujano
JOIN persona          pe  ON pe.id_persona          = pl.id_persona
WHERE r.decision = 'Rechazada';

-- Resumen de satisfacción y calificación media obtenida por cada hospital.
CREATE OR REPLACE VIEW vw_calificacion_resumen_hospital AS
SELECT 
    h.id_hospital,
    h.nombre AS hospital,
    COUNT(ch.id_calificacion_hospital) AS total_evaluaciones,
    ROUND(AVG(ch.puntuacion), 2)       AS promedio_estrellas
FROM hospital h
LEFT JOIN episodio ep ON ep.id_hospital = h.id_hospital
LEFT JOIN calificacion_hospital ch ON ch.id_episodio = ep.id_episodio
WHERE h.es_interno = TRUE
GROUP BY h.id_hospital, h.nombre;


/* ============================================================================
   TRIGGERS DE REGLAS DE NEGOCIO E INTEGRIDAD COMPLEJA
   ============================================================================ */

-- 1. Regla: La fecha de nacimiento no puede ser posterior a la fecha actual.
CREATE OR REPLACE FUNCTION fn_check_persona_fecha_nacimiento()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.fecha_nacimiento > CURRENT_DATE THEN
        RAISE EXCEPTION 'Regla de Negocio Violada: La fecha de nacimiento (%) no puede ser futura.',
            NEW.fecha_nacimiento;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_check_persona_fecha_nacimiento
BEFORE INSERT OR UPDATE ON persona
FOR EACH ROW EXECUTE FUNCTION fn_check_persona_fecha_nacimiento();


-- 2. Regla: La fecha y hora de egreso no puede ser anterior a la de ingreso.
CREATE OR REPLACE FUNCTION fn_check_fecha_egreso()
RETURNS TRIGGER AS $$
DECLARE
    v_fecha_ingreso TIMESTAMPTZ;
BEGIN
    SELECT fecha_hora_ingreso INTO v_fecha_ingreso
    FROM ingreso
    WHERE id_ingreso = NEW.id_ingreso;

    IF NEW.fecha_hora_egreso < v_fecha_ingreso THEN
        RAISE EXCEPTION 'Regla Clínica Violada: La fecha y hora de egreso (%) no puede preceder al ingreso (%).',
            NEW.fecha_hora_egreso, v_fecha_ingreso;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_check_fecha_egreso
BEFORE INSERT OR UPDATE ON egreso
FOR EACH ROW EXECUTE FUNCTION fn_check_fecha_egreso();


-- 3. Regla: Límite estricto de máximo 4 quirófanos por hospital interno en Cirugía.
CREATE OR REPLACE FUNCTION fn_check_limite_quirofanos()
RETURNS TRIGGER AS $$
DECLARE
    v_tipo_unidad      VARCHAR(30);
    v_total_quirofanos INTEGER;
BEGIN
    IF NEW.tipo = 'Quirofano' THEN
        SELECT tu.nombre INTO v_tipo_unidad
        FROM unidad_hospital uh
        JOIN tipo_unidad tu ON tu.id_tipo_unidad = uh.id_tipo_unidad
        WHERE uh.id_unidad_hospital = NEW.id_unidad_hospital;

        IF v_tipo_unidad NOT ILIKE 'Cirug%' THEN
            RAISE EXCEPTION 'Regla Hospitalaria: Un quirofano solo puede habilitarse en la unidad de Cirugia (asignado a: %)',
                v_tipo_unidad;
        END IF;

        SELECT COUNT(*) INTO v_total_quirofanos
        FROM espacio_atencion ea
        WHERE ea.id_unidad_hospital = NEW.id_unidad_hospital
          AND ea.tipo = 'Quirofano'
          AND ea.id_espacio <> COALESCE(NEW.id_espacio, -1);

        IF v_total_quirofanos >= 4 THEN
            RAISE EXCEPTION 'Regla Hospitalaria: El hospital ya cuenta con los 4 quirofanos reglamentarios habilitados.';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_check_limite_quirofanos
BEFORE INSERT OR UPDATE ON espacio_atencion
FOR EACH ROW EXECUTE FUNCTION fn_check_limite_quirofanos();


-- 4. Regla: Exclusividad de unidades en hospitales propios de la red.
CREATE OR REPLACE FUNCTION fn_check_unidad_hospital_interno()
RETURNS TRIGGER AS $$
DECLARE
    v_es_interno BOOLEAN;
BEGIN
    SELECT es_interno INTO v_es_interno
    FROM hospital
    WHERE id_hospital = NEW.id_hospital;

    IF v_es_interno IS NOT TRUE THEN
        RAISE EXCEPTION 'Regla Institucional: No se pueden registrar unidades medicas en centros externos. Estos solo aplican para referencias y traslados.';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_check_unidad_hospital_interno
BEFORE INSERT OR UPDATE ON unidad_hospital
FOR EACH ROW EXECUTE FUNCTION fn_check_unidad_hospital_interno();


-- 5. Regla: El correlativo de cuota de pago no puede exceder las cuotas pactadas.
CREATE OR REPLACE FUNCTION fn_check_cuota_pago()
RETURNS TRIGGER AS $$
DECLARE
    v_cuotas_max SMALLINT;
BEGIN
    SELECT numero_cuotas INTO v_cuotas_max
    FROM factura
    WHERE id_factura = NEW.id_factura;

    IF NEW.numero_cuota > v_cuotas_max THEN
        RAISE EXCEPTION 'Regla Financiera: El numero de cuota (%) sobrepasa el financiamiento convenido en la factura (% cuotas).',
            NEW.numero_cuota, v_cuotas_max;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_check_cuota_pago
BEFORE INSERT OR UPDATE ON pago
FOR EACH ROW EXECUTE FUNCTION fn_check_cuota_pago();


-- 6. Regla: Coherencia entre categoría laboral de personal y rol en equipo quirúrgico.
CREATE OR REPLACE FUNCTION fn_check_rol_equipo_quirurgico()
RETURNS TRIGGER AS $$
DECLARE
    v_tipo_personal VARCHAR(30);
BEGIN
    SELECT tipo_personal INTO v_tipo_personal
    FROM personal
    WHERE id_personal = NEW.id_personal;

    IF NEW.rol IN ('Cirujano principal', 'Cirujano ayudante', 'Anestesiologo') AND v_tipo_personal <> 'Medico' THEN
        RAISE EXCEPTION 'Regla Quirurgica: El rol de % requiere acreditacion de Medico (registrado como: %)',
            NEW.rol, v_tipo_personal;
    END IF;

    IF NEW.rol IN ('Enfermero instrumentista', 'Enfermero circulante') AND v_tipo_personal <> 'Enfermero' THEN
        RAISE EXCEPTION 'Regla Quirurgica: El rol de % requiere un profesional de Enfermeria',
            NEW.rol;
    END IF;

    IF NEW.rol = 'Practicante de medicina' AND v_tipo_personal <> 'Practicante de medicina' THEN
        RAISE EXCEPTION 'Regla Quirurgica: Rol reservado para personal clasificado como Practicante de medicina';
    END IF;

    IF NEW.rol = 'Practicante de enfermeria' AND v_tipo_personal <> 'Practicante de enfermeria' THEN
        RAISE EXCEPTION 'Regla Quirurgica: Rol reservado para personal clasificado como Practicante de enfermeria';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_check_rol_equipo_quirurgico
BEFORE INSERT OR UPDATE ON cirugia_equipo_medico
FOR EACH ROW EXECUTE FUNCTION fn_check_rol_equipo_quirurgico();


-- 7. Regla: Consulta externa se liquida en un único pago (1 cuota).
CREATE OR REPLACE FUNCTION fn_check_cuotas_factura()
RETURNS TRIGGER AS $$
DECLARE
    v_tiene_otros_conceptos BOOLEAN;
BEGIN
    -- Comprobar si existen conceptos distintos a Consulta en el detalle
    SELECT EXISTS (
        SELECT 1 
        FROM factura_detalle 
        WHERE id_factura = NEW.id_factura 
          AND concepto <> 'Consulta'
    ) INTO v_tiene_otros_conceptos;

    -- Si la factura solo contiene consultas, no se permite el financiamiento en cuotas
    IF NOT v_tiene_otros_conceptos AND NEW.numero_cuotas > 1 THEN
        -- Comprobamos si efectivamente tiene al menos un concepto de Consulta
        IF EXISTS (SELECT 1 FROM factura_detalle WHERE id_factura = NEW.id_factura AND concepto = 'Consulta') THEN
            RAISE EXCEPTION 'Regla Financiera: Las atenciones de Consulta Externa deben cancelarse en un unico pago.';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_check_cuotas_factura
BEFORE UPDATE ON factura
FOR EACH ROW EXECUTE FUNCTION fn_check_cuotas_factura();


-- 8. Regla: Integridad cruzada entre paciente de la cita y del episodio de consulta.
CREATE OR REPLACE FUNCTION fn_check_coherencia_paciente_consulta()
RETURNS TRIGGER AS $$
DECLARE
    v_paciente_cita     INTEGER;
    v_paciente_episodio INTEGER;
BEGIN
    SELECT id_paciente INTO v_paciente_cita
    FROM cita
    WHERE id_cita = NEW.id_cita;

    SELECT id_paciente INTO v_paciente_episodio
    FROM episodio
    WHERE id_episodio = NEW.id_episodio;

    IF v_paciente_cita <> v_paciente_episodio THEN
        RAISE EXCEPTION 'Inconsistencia Clinica: El paciente de la cita (%) no coincide con el del episodio (%).',
            v_paciente_cita, v_paciente_episodio;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_check_coherencia_paciente_consulta
BEFORE INSERT OR UPDATE ON consulta
FOR EACH ROW EXECUTE FUNCTION fn_check_coherencia_paciente_consulta();

-- ============================================================================
-- FIN
-- ============================================================================
